### ISSUE TITLE
Optional raw data on emitText

### ISSUE THREAD

**Issue by mritzco** [assistunion/xml-stream#79]
My XML contains HTML in some data nodes that is escaped on the emitText function.

What would be the best way to implement this (I can do and send a pull request)

- add an option parameter (object) to return unescaped text?
- expose the escape function?

Or any better way?

**Comment by alopes** [comment]
why not just wrapping your content with cdata?

example:
`<![CDATA[ __your___html___content ]]>`

**Comment by mritzco** [comment]
It beats me why cdata is not used at all but I'm not the owner of the format. These are TMX files used for data exchange in TMS (Translation) systems as any change might break on some platforms I'm trying to stick to the samples.
